baseurl = "https://NerveMilk.github.io/"
languageCode = "en-us"
title = "Nerve Milk 神经奶"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "BlahBlahBlah"
    url = "/"
    weight = 1
[[menu.main]]
    name = "WTF"
    url = "/wtf/"
    weight = 2

[params]
    description = "weird Chinese sci-fi stories."
    footer = ""
