baseurl = "https://NerveMilk.github.io/"
languageCode = "en-us"
title = "NERVEMILK | 神经奶"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Stories"
    url = "/"
    weight = 1
# [[menu.main]]
#     name = "Projects"
#     url = "/projects/"
#     weight = 2
# [[menu.main]]
#     name = "Shop"
#     url = "/shop/"
#     weight = 3
[[menu.main]]
    name = "Instagram"
    url = "https://www.instagram.com/nervemilk/"
    weight = 4
[[menu.main]]
    name = "About"
    url = "/wtf/"
    weight = 5
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[params]
    description = "weird Chinese sci-fi stories."
    footer = ""
