baseurl = "https://NerveMilk.github.io/"
languageCode = "en-us"
title = "神经奶"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Stories"
    identifier = "stories"
    url = "/"
    weight = 1
[[menu.main]]
    name = "News"
    url = "/news/"
    identifier = "news"
    weight = 2
[[menu.main]]
    name = "Instagram"
    identifier = "ins"
    url = "https://www.instagram.com/nervemilk/"
    weight = 3
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 4

[params]
    description = ""
    footer = ""
